package ClasesVentanas;

import java.io.IOException;
import java.io.RandomAccessFile;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlVentanas.java
 *
 * Created on 11-21-2011, 11:41:49 PM
 */
/**
 *
 * @author NIGHTMARE
 */
public abstract class ControlVentanas extends javax.swing.JFrame {
    public static IniciarSesion inicio;
    static Registrar registro;
    static FaceMain face;
    static RandomAccessFile registros=null;
    /** Creates new form ControlVentanas */
    public ControlVentanas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void crearRegistro(){
        registro=new Registrar("Registrar una nueva cuenta"); 
    }
    public static void crearFace(){
        face=new FaceMain("FACEBIN, Página Principal");
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
            @Override
            public void run(){
                try{
                    registros=new RandomAccessFile("registro.buenr","rw");
                }catch(IOException e){
                    System.out.println(e.getMessage());
                }
                 
                inicio=new IniciarSesion();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
